controller_joint_names: ['', 'LR1_joint', 'LR2_joint', 'LR3_joint', 'LR4_joint', 'LR5_joint', 'LR6_joint', 'LR7_joint', 'LR8_joint', 'LR9_joint', 'LR10_joint', 'LR11_joint', 'LR12_joint', 'LR13_joint', 'LR14_Joint', ]
