controller_joint_names: ['', 'RR1_joint', 'RR2_joint', 'RR3_joint', 'RR4_joint', 'RR5_joint', 'RR6_joint', 'RR7_joint', 'RR8_joint', 'RR9_joint', 'RR10_joint', 'RR11_joint', 'RR12_joint', 'RR13_joint', 'RR14_joint', ]
